export enum EShortcutEv {
  MAKE_OR_CANCEL_REQUEST,
  SELECT_GET_METHOD,
  SELECT_POST_METHOD,
  SELECT_PUT_METHOD,
  SELECT_PATCH_METHOD,
  SELECT_DELETE_METHOD,
  FOCUS_URL,
  COPY_URL,
  TOGGLE_PROXY,
  SHOW_SHORTCUTS,
}
