name: App
on:
  push:
    branches: ["master"]
    paths: ["app/**"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap-app
      - run: npm --prefix ./app run lint.strict
  checkTypes:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap-app
      - run: npm --prefix ./app run check-types
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: [lint, checkTypes]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap-app
      - name: Build
        run: npm --prefix ./app run build
      - name: Deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: app/dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
